services:
  # A Docker web service
  - type: web
    name: Allmx
    env: docker
    repo: https://github.com/0ALLMX01/AList-Aria2-Render.git # optional
    region: Singapore # optional (defaults to oregon)
    plan: free # optional (defaults to starter)
    healthCheckPath: /
    envVars:
      - key: DB_TYPE
        # value: sqlite3
        sync: false
      - key: db.bit.io
        # value: db_host
        sync: false
      - key: 5432
        # value: 5432
        sync: false
      - key: allmx
        # value: db_user
        sync: false
      - key: v2_42R3B_uWaqZzXKjsHRnPi2cgQ9Lxe
        # value: db_password
        sync: false
      - key: allmx/Yaemiko
        # value: db_name
        sync: false
      - key: DB_TABLE_PREFIX
        # value: rlist
        sync: false
